---
title: "Dispersion of 1st & 2nd Largest Eigenvalues"
author: "Taqi"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../R/header.R")
.src(d = 1)
```

# 25x25 Complex Hermitian Matrix

```{r}
P <- RME_norm(N = 25, cplx = T, herm = T, size = 1000)
spec_P <- P %>% spectrum(order = 1:2, components = T)
spec_P %>% spectrum.scatterplot()
```

```{r}
#.dispersion_matrix(P[[1]], diff_abs = T)
#.dispersion_matrix(P[[1]], diff_abs = F)
```

\newpage

# Within matrix

### Difference of Absolutes

```{r}
pairs_12 <- data.frame(i = 1, j = 2)
disps <- P %>% dispersion(diff_abs = T, components = F, norm = F, pairs = pairs_12)
disps %>% dispersion.histogram(bins = 30)
```

### Absolute Difference

### Without Resolving Components

```{r}
pairs_12 <- data.frame(i = 1, j = 2)
disps <- P %>% dispersion(diff_abs = F, components = F, pairs = pairs_12)
disps %>% dispersion.histogram()
```

### Resolving Components

```{r}
disps <- P %>% dispersion(diff_abs = F, components = T, norm = F, pairs = pairs_12)
disps %>%
  ggplot(aes(x = Disp_Re)) +
  geom_histogram()
disps %>%
  ggplot(aes(x = Disp_Im)) +
  geom_histogram()
```

\newpage

# Within ensemble

```{r}
specP <- P %>% spectrum()
```

### Difference of Absolutes

```{r}
spec1 <- (specP %>% filter(Order == 1))$Norm
spec2 <- (specP %>% filter(Order == 2))$Norm
```

```{r}
disps_cross <- data.frame(Dispersion = do.call("c",map(seq_along(spec1), function(x){x - spec2})))
```

```{r}
disps_cross %>%
  ggplot(mapping = aes(Dispersion)) +
  geom_histogram(bins = 250) +
  labs(title = "Distribution of |Lam_1 - Lam_2|")
```


### Absolute Difference

```{r}
specP <- P %>% spectrum(components = F)
spec1 <- (specP %>% filter(Order == 1))$Eigenvalue
spec2 <- (specP %>% filter(Order == 2))$Eigenvalue
```

```{r}
disps_cross2 <- data.frame(Dispersion = do.call("c",map(seq_along(spec1), function(x){abs(x - spec2)})))
disps_cross2 %>%
  ggplot(mapping = aes(Dispersion)) +
  geom_histogram(bins = 250)
```


