---
title: "fit_betadisp"
author: "Ali Taqi"
date: "3/7/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("../R/header.R")
library(gglm)
.src(d = 1)
```

```{r}
# Helper function taking in a fitted object and the dispersions to plot residuals against dispersions
disp_res_plot <- function(fit_disp, disp_ens){
  res <- fit_disp$residuals
  disp_ens$res <- res
  # Dispersion v. residuals plot
  ggplot() + 
    geom_point(data = disp_ens, mapping = aes(Dispersion, res, color = OrderDiff)) +
    scale_color_gradient(low = "blue", high = "red")
}
# Master function returning list of objects to display
model_plots <- function(disp_ens, intercept = F){
  if(intercept){fit_disp <- lm(Dispersion ~ OrderDiff, data = disp_ens)}
  else{
    intercept <- 0
    fit_disp <- lm(I(Dispersion - intercept) ~ 0 + OrderDiff, data = disp_ens)
  }
  summary <- summary(fit_disp)
  summary_plots <- gglm(data = fit_disp)
  # Dispersion v. residuals plot
  disp_plot <- disp_res_plot(fit_disp, disp_ens)
  list(summary, summary_plots, disp_plot)
}
```

## Fitting Dispersions of Beta = 4, N = 20

\newpage

## The Ensemble

```{r}
set.seed(23)
# Initialize ensemble
ens <- RME_beta(N = 20, beta = 4, size = 250)

# Spectra plots
spec_ens <- ens %>% spectrum()
spec_ens %>% spectrum.scatterplot()
# spec_ens %>% spectrum.histogram(imaginary = F, bins = 50)

# Dispersion plots
disp_ens <- ens %>% dispersion
disp_ens %>% dispersion.scatterplot()
```

## Linear Model

```{r}
model <- model_plots(disp_ens, intercept = F)
model[[1]]
```

\newpage

```{r, fig.height = 5}
model[[2]]
```

```{r, fig.height = 4}
model[[3]]
```

\newpage

## Fitting Dispersions of Beta = 4, N = 50

## The Ensemble

```{r}
set.seed(23)
# Initialize ensemble
ens <- RME_beta(N = 40, beta = 4, size = 50)

# Spectra plots
spec_ens <- ens %>% spectrum()
spec_ens %>% spectrum.scatterplot()
# spec_ens %>% spectrum.histogram(imaginary = F, bins = 50)

# Dispersion plots
disp_ens <- ens %>% dispersion
disp_ens %>% dispersion.scatterplot()
```

\newpage

## Linear Model

```{r}
model <- model_plots(disp_ens, intercept = F)
model[[1]]
```

\newpage

```{r, fig.height = 5}
model[[2]]
```

```{r, fig.height = 4}
model[[3]]
```