---
title: "Eigenvectors of Symmetric Matrices"
author: "Ali Taqi"
date: "11/4/2020"
output: pdf_document
header-includes:
  - \newcommand{\R}{\mathbb{R}}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
# Load libraries
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "symm_evc.R")
source(file = "../R/eigenvectors.R")
source(file = "../R/eigenmetrics.R")
```

# Computational Evidence: Real Symmetric Matrices have Real Eigenvectors

```{r}
unif_fpos <- function(M,f=T,ep){
  # unless specifically initialized, a random fraction will be chosen
  if(f){
    f <- runif(1,0,1)
    paste("f: ",f,sep="")
  }
  b <- f
  a <- (f-1)
  dist <- data.frame(x = runif(M**2, ep*a, ep*b))
  dist <- dist %>% mutate(x_neg = ifelse(x < 0,yes = 1, no = 0))
  dist
}
```

```{r}
make_symm <- function(dist){
  N <- sqrt(length(dist$x))
  P <- matrix(data = dist$x, nrow = N, ncol = N)
  LT <- lower.tri(P)
  UT <- upper.tri(P)
  P[LT] <- P[UT]
  P
}
```

```{r}
# Uniform matrix with symm = T
RM_symm(5,0.5,10)
```

# Simulation

```{r}
simulate_by_f <- function(f,M_max,ep_max,draws){
  M_vec <- sample(1:M_max, draws, replace = T)
  ep_vec <- sample(1:ep_max, draws, replace = F)
  table <- data.frame(M = M_vec, ep = rep(ep_vec,length(M_vec)))

  bool_vec <- rep(NA, length(table$M))

  for(i in 1:length(table$M)){
    S_curr <- RM_symm(table$M[i],f,table$ep[i])
    bool_vec[i] <- check_real_eigenvectors(eigen_frame(S_curr))
  }
  cbind(table,bool_vec)
}

plot_f_table <- function(table, f){
  ggplot() + 
    geom_point(data = table, aes(x=M, y=ep, color = factor(bool_vec))) +
    labs(color = "EV Real", title = paste("f = ",f,sep=""))
}
```

```{r, cache = T}
table <- simulate_by_f(f = 0.1, M_max = 15, ep_max = 50, draws = 50)
head(table)
plot_f_table(table, f = 0.1)
```

```{r, cache = T}
#table <- simulate_by_f(f = 0.5, M_max = 15, ep_max = 250, draws = 250)
#head(table)
#plot_f_table(table, f = 0.5)
```

```{r, cache = T}
#table <- simulate_by_f(f = 0.9, M_max = 15, ep_max = 250, draws = 250)
#head(table)
#plot_f_table(table, f = 0.9)
```
