---
title: "Eigenvectors of Symmetric Matrices"
author: "Ali Taqi"
date: "11/4/2020"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "R/sym_eigen.R")
```

```{r}
vec_iter <- function(it, fun){
  vec <- rep(NA, it)
  for(i in 1:it){
    vec[i] <- fun()
  }
  vec
}
all_ones <- function(){
  1
}
ret <- vec_iter(10,all_ones)
```

```{r}
M <- 3
f <- 0.5
ep <- 100
dist <- unif_frand(M = M, f = f, ep = ep)
S <- make_symm(dist)
isSymmetric(S)
diff <- f - pos_entries(S)
diff
```

```{r}
M_vec <- 2:100
diff_props <- function(M){
  f <- 0.5
  ep <- 100
  dist <- unif_frand(M = M, f = f, ep = ep)
  S <- make_symm(dist)
  f - pos_entries(S)
}
iter_vec <- rep(NA, length(M_vec))
for(M in M_vec){
  iter_vec[M-1] <- diff_props(M)
}
ggplot() + geom_point(data = data.frame(x = M_vec, y = iter_vec), aes(x=x,y=y))
```

```{r}
# add matrix so that we plot(ep,M) on xy plane and color value of diff to show 2d relation of convergence of our method
M_vec <- 2:100
ep_vec <- 1:100
diff_props <- function(M, f, ep){
  S <- RM_symm(M,f,ep)
  f - pos_entries(S)
}
iter_vec <- rep(NA, length(M_vec))
for(M in M_vec){
  iter_vec[M-1] <- diff_props(M)
}
ggplot() + geom_point(data = data.frame(x = M_vec, y = iter_vec), aes(x=x,y=y))
```

