---
title: "Chapter 2 Graphics"
author: "Taqi"
#date: "4/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("../R/header.R")
.src(1)
```

```{r}
set.seed(23)
run <- T
if(run)
{
save <- T
if(save){ggsave(filename = "test.pdf", path = "chap2", width = 10.5, height = 7)}
}
```

# Workspace

```{r}
# Set parameters
N <- 50
# Generate random matrix ensemble
ens <- RME_norm(N = N, size = 20)
# Get dispersion
ens_disp <- ens %>% dispersion_parallel(pairs = "lower")
# Generate plot
ens_disp %>% dispersion.scatterplot(metric = "id_diff_norm") / ens_disp %>% dispersion.scatterplot(metric = "abs_diff")
```

```{r}
# Set parameters
N <- 50
# Generate random matrix ensemble
ens <- RME_norm(N = N, symm = T, size = 20)
# Get spectrum
ens %>% spectrum.scatterplot()
# Get dispersion
ens_disp <- ens %>% dispersion_parallel(pairs = "lower")
# Generate plot
ens_disp %>% dispersion.scatterplot(metric = "id_diff_norm") / ens_disp %>% dispersion.scatterplot(metric = "abs_diff")
```

```{r}
# Set parameters
N <- 50
# Generate random matrix ensemble
ens <- RME_beta(N = N, beta = 2, size = 20)
# Get spectrum
ens %>% spectrum.scatterplot()
# Get dispersion
ens_disp <- ens %>% dispersion_parallel(pairs = "lower")
# Generate plot
ens_disp %>% dispersion.scatterplot(metric = "id_diff_norm") / ens_disp %>% dispersion.scatterplot(metric = "abs_diff")
```

# Section 2

```{r}
set.seed(23)
run <- T
if(run)
{
# Set parameters
N <- 50
# Generate random matrix ensemble
ens <- RME_norm(N = N, size = 20)
# Get dispersion
ens_disp <- ens %>% dispersion_parallel(pairs = "lower")
# Generate plot
ens_disp %>% dispersion.scatterplot(metric = "id_diff_norm") / ens_disp %>% dispersion.scatterplot(metric = "abs_diff")
# Save plot
save <- F
if(save){ggsave(filename = "2-1-2_comparison.pdf", path = "chap2", width = 10.5, height = 7)}
}
```

