---
title: "Chapter 4 Graphics"
author: "Taqi"
#date: "4/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("../R/header.R")
.src(1)
```

```{r, eval = FALSE}
set.seed(23)
run <- F
if(run){
  # Set parameters
  N <- 50
  # Generate ensemble
  ens <- RME_norm(N = N, symm = T, size = 300)
  if(F){  
    # Get spectrum 
    ens_spec <- ens %>% spectrum_par()
    write.csv(ens_spec, "data/spec_order_density.csv", row.names = F)
  } else{
    ens_spec <- read_csv("data/spec_order_density.csv")
  }
  # Get plot
  ens_plot <- order.summary(ens_spec, Variance_Re)
  ens_plot
  # Save plot
  save <- T
  if(save){
    ggsave(filename = "2-2-1_spec_order_summary.pdf", path = "chap2", width = 10.5, height = 7)
  }
}
```

# The Ensemble

```{r, echo = T}
# ===================================================
#                       Setup
# ===================================================
set.seed(23)
# Set parameters
N <- 25
beta <- 2
size <- 300
# Beta ensemble
ens <- RME_beta(N, beta, size)
spec_ens <- spectrum_parallel(ens, sort_norms = FALSE)
spec_ens_sg <- spectrum_parallel(ens, singular = TRUE)
# ===================================================
#              Simulation: Sign-Sorted
# ===================================================
#RRRRRRRRRRRRRRRRRRRRRRRRRRRR#
run <- T
#RRRRRRRRRRRRRRRRRRRRRRRRRRRR#
if(run)
{
## === Real ===
spec_ens %>% order.scatterplot(component = Re) / spec_ens %>% order.density(component = Re)
# Save plot
save <- T
if(save){ggsave(filename = "4-2_Re_spec.pdf", path = "chap4", width = 10.5, height = 7)}
## === Norm ===
spec_ens %>% order.scatterplot(component = Norm) / spec_ens %>% order.density(component = Norm)
# Save plot
save <- T
if(save){ggsave(filename = "4-2_Norm_spec.pdf", path = "chap4", width = 10.5, height = 7)}
}

#==============================#
#  Summary of Order Statistics
#==============================#
#RRRRRRRRRRRRRRRRRRRRRRRRRRRR#
run <- T
#RRRRRRRRRRRRRRRRRRRRRRRRRRRR#
if(run)
{
## === Real ===
spec_ens %>% order.summary(component = Mean_Re) / spec_ens %>% order.summary(component = Variance_Re)
# Save plot
save <- T
if(save){ggsave(filename = "4-2_Re_summary.pdf", path = "chap4", width = 10.5, height = 7)}
## === Norm ===
spec_ens %>% order.summary(component = Mean_Norm) / spec_ens %>% order.summary(component = Variance_Norm)
# Save plot
save <- T
if(save){ggsave(filename = "4-2_Norm_summary.pdf", path = "chap4", width = 10.5, height = 7)}
}
# ===================================================
#            Simulation: Singular Values
# ===================================================
#RRRRRRRRRRRRRRRRRRRRRRRRRRRR#
run <- T
#RRRRRRRRRRRRRRRRRRRRRRRRRRRR#
if(run)
{
## Norm
spec_ens_sg %>% order.scatterplot(component = Norm) / spec_ens_sg %>% order.density(component = Norm)
save <- T
if(save){ggsave(filename = "4-2_SING_Norm_spec.pdf", path = "chap4", width = 10.5, height = 7)}
##=============================##
## Summary of Order Statistics
##=============================##
## Norm
spec_ens_sg %>% order.summary(component = Mean_Norm) / spec_ens_sg %>% order.summary(component = Variance_Norm) 
save <- T
if(save){ggsave(filename = "4-2_SING_Norm_summary.pdf", path = "chap4", width = 10.5, height = 7)}
}
```

