---
title: "ch2-order"
author: "Taqi"
date: "4/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("../R/header.R")
source("orderPlots.R")
library(future)
library(RMAT)
library(wesanderson)
.src(1)
```

```{r}
wes_pal <- wes_palette("Zissou1", 100, type = "continuous")
```

```{r}
set.seed(23)
# Set parameters
N <- 15
size <- 2500
alpha <- 0.35
bins <- 75
# Generate beta ensembles
beta2 <- RME_beta(N = N, beta = 2, size = size)
beta4 <- RME_beta(N = N, beta = 4, size = size)
```

```{r}
# Generate their sign-ordered spectra
if(F){
  beta2_sign <- beta2 %>% spectrum_par(norm_order = FALSE)
  beta4_sign <- beta4 %>% spectrum_par(norm_order = FALSE)
  # Save the spectra
  write.csv(beta2_sign, "data/beta2-sign.csv", row.names = F) 
  write.csv(beta4_sign, "data/beta4-sign.csv", row.names = F) 
} else{
  beta2_sign <- read_csv("data/beta2-sign.csv")
  beta4_sign <- read_csv("data/beta4-sign.csv")
}
# Generate their norm-ordered spectra
if(F){
  beta2_norm <- beta2 %>% spectrum_par(norm_order = TRUE)
  beta4_norm <- beta4 %>% spectrum_par(norm_order = TRUE)
  # Save the spectra
  write.csv(beta2_norm, "data/beta2-norm.csv", row.names = F) 
  write.csv(beta4_norm, "data/beta4-norm.csv", row.names = F) 
} else{
  beta2_norm <- read_csv("data/beta2-norm.csv")
  beta4_norm <- read_csv("data/beta4-norm.csv")
}
```

```{r}
plot2 <- plot_d_Re(beta2_norm, ordering = "Norm", class = "Beta-2 Ensemble") + ylim(c(0,1.3))
ggsave(filename = "beta2_spec.jpg", path = "chap4", width = 10.5, height = 5.25)
plot4 <- plot_d_Re(beta4_norm, ordering = "Norm", class = "Beta-4 Ensemble") + ylim(c(0,1.3))
ggsave(filename = "beta4_spec.jpg", path = "chap4", width = 10.5, height = 5.25)
```


```{r}
plot2 <- plot_d_Re(beta2_norm, ordering = "Norm", class = "Beta-2 Ensemble") + ylim(c(0,1.3))
ggsave(filename = "beta2_spec.jpg", path = "chap4", width = 10.5, height = 5.25)
plot4 <- plot_d_Re(beta4_norm, ordering = "Norm", class = "Beta-4 Ensemble") + ylim(c(0,1.3)) + labs(y = "") + theme(legend.position = "none")
ggsave(filename = "beta4_spec.jpg", path = "chap4", width = 10.5, height = 5.25)
plot2+plot4
ggsave(filename = "beta24_spec.jpg", path = "chap4", width = 10.5, height = 5.25)
```

```{r}
order.summary(beta2_sign, Variance_Re)
order.summary(beta4_sign, Variance_Re)
```

