---
title: "Markov Chain Simulations"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
col_str <- "blue"
```

# Generating Random Matrices

```{r row_fxns}
# generates rows of size P which are valid probability distributions
r0 <- function(M){
  prob <- runif(M,0,1)
  prob/sum(prob) # return normalized random row vector
}

r1 <- function(M){
  prob <- runif(M,0,1)
  num_zeros <- sample(1:(M-1),1)
  choices <- sample(1:M, num_zeros)
  prob[choices] <- 0
  prob/sum(prob) # return normalized random row vector
}
```

```{r random_matrix}
# initialize random P
rand_M <- function(M,row_fxn){
  P <- matrix(rep(NA, M * M), ncol = M)  # create transition matrix
  for(i in 1:M){P[i,] = row_fxn(M)}
  P
}
```

\newpage

# Eigenvectors

```{r setup_eigen}
M <- 8 # number of states
P <- rand_M(M,r1) # initialize P 
eigen_vecs <- data.frame(eigen(P)[2])
```

```{r complex_plot}
cols <- 3 # set 3 to hold (re,im) pair and whose row it belongs to
complex <- matrix(rep(NA,cols*M*M), ncol = cols)
colnames(complex) <- c("Re","Im","v")
for(i in 1:M){
  for(j in 1:M){
    curr <- eigen_vecs[i,j]
    complex[M*(i-1) + j, ] <- c(Re(curr),Im(curr),i) 
  }
}
```

```{r eigen_plot}
r <- 1
ep <- 0.5
ggplot(complex) + 
  geom_point(aes(x = Re, y = Im, color = v)) + 
  labs(x = "Re", y = "Im", title = "Distribution of Eigenvectors in the Complex Plane") +
  xlim(-(r+ep),r+ep) + ylim(-r,r) +
  ggforce::geom_circle(aes(x0=0,y0=0,r=r), color = "steelblue")
```

\newpage

# Convergence

```{r setup_convg}
set.seed(23)
M <- 12 
P <- rand_M(M,r1)
eigen_vecs <- data.frame(eigen(P)[2])
st <- eigen_vecs[1,1] # choose reference vector to find distance from
it <- 30 # number of iterations of transition matrix
```

```{r longrun}
evolve <- function(pi){
  # simulate and record evolution of pi
  vals <- matrix(rep(NA, (M+1) * it), ncol = (M+1))
  # rename the columns
  str_vec <- rep(NA, M)
  for(i in 1:M){str_vec[i] = paste("x",i,sep="")}
  colnames(vals) <- c("n",str_vec)
  # evolve pi 
  for(i in 1:it){
    vals[i, ] = c(i, pi %*% matrix.power(P,i))
  }
  #store the values in a dataframe
  vals_ <- data.frame(vals) # store indices as base df in case they are needed
  vals <- subset(vals_, select = -c(n))
  vals
}
```

```{r euclidean_plot}
distance <- function(pi,ref_dist){
  #plot difference from a reference/stationary distribution
  diff <- rbind(evolve(pi),ref_dist)
  dist_vec <- rep(0, it)
  for(i in 1:it){
    curr_dist <- stats::dist(diff[c(i,it+1),], method = "euclidean")
    dist_vec[i] <- curr_dist
  }
  data.frame(dist_vec)
}
plot_d <- function(init,ref){
  dist_vec <- distance(init,ref)
  dist_plot <- ggplot(dist_vec, mapping = aes(x = 1:it, y = dist_vec)) + 
    geom_point(color = col_str) + geom_line(color = col_str) +
    labs(x = "n", y = "Euclidean Distance")
  dist_plot
}
```

## Simulating convergence using initial distributions of row function 1

```{r, fig.height = 10}
p1 <- plot_d(r1(M),st)
p2 <- plot_d(r1(M),st)
p3 <- plot_d(r1(M),st)
p4 <- plot_d(r1(M),st)
p5 <- plot_d(r1(M),st)
p6 <- plot_d(r1(M),st)
(p1+p2)/(p3+p4)/(p5+p6)
```

```{r, include = FALSE}
col_str <- "red"
plot_d <- function(init,ref){
  dist_vec <- distance(init,ref)
  dist_plot <- ggplot(dist_vec, mapping = aes(x = 1:it, y = dist_vec)) + 
    geom_point(color = col_str) + geom_line(color = col_str) +
    labs(x = "n", y = "Euclidean Distance")
  dist_plot
}
```

## Simulating convergence using initial distributions of row function 0

```{r, fig.height = 10}
p1 <- plot_d(r0(M),st)
p2 <- plot_d(r0(M),st)
p3 <- plot_d(r0(M),st)
p4 <- plot_d(r0(M),st)
p5 <- plot_d(r0(M),st)
p6 <- plot_d(r0(M),st)

(p1+p2)/(p3+p4)/(p5+p6)
```
