---
title: "Computational Simulation of the Eigenvalues of a Stochastic Matrix"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(matrixcalc)
library(gganimate)
# Load files
source(file = "../R/matrices.R")
source(file = "../R/eigenvectors.R")
source(file = "../R/simulate.R")
source(file = "../R/analyze.R")
# global parameters
bool_plot <- T
bool_loud <- T
bool_animate <- F
```

```{r}
# General function
  evl_erdos <- function(M,p,it){
  # Generate initial matrix
  set.seed(23)
  P <- RM_erdos(M, p_sparse = p, stoch = T)
  evals <- eval_frame(P)
  # Attach p index
  p_sparsity <- rep(as.factor(p), M)
  # Main loop
  evl_stack <- cbind(evals, p_sparsity)
  for(i in 1:it){
    P <- RM_erdos(4, p_sparse = p, stoch = T)
    evl_stack <- rbind(evl_stack, cbind(eval_frame(P), p_sparsity))
  }
  evl_stack
}
```

```{r}
## OVERWRITE FUNCTION
# Plots the eigenvalues of a given matrix P
eval_plot <- function(P, mat_type=""){
  # Check if we have a stack or singular matrix
  if(nrow(P) == ncol(P)){
    array <- eval_frame(P)
  } else{
    array <- P 
  }
  # Plot parameters
  r <- 1
  r_ep <- r + 0.5
  # Plot
  ggplot(array) + 
    geom_point(aes(x = Re, y = Im, col = as.factor(p_sparsity))) + 
    labs(x = "Re", y = "Im", title = paste("Eigenvalues of ",mat_type," Matrix",sep = "")) +
    xlim(-r_ep,r_ep) + ylim(-r,r) +
    ggforce::geom_circle(aes(x0 = 0, y0 = 0, r = r), color = "steelblue") +
    scale_color_discrete(name = "Row_i") +
    scale_x_continuous(name = "Re(r_i)") +
    scale_y_continuous(name = "Im(r_i)") +
    coord_fixed(ratio = 1) +
    theme(legend.position = "none")
}
```


```{r}
# Document parameters
M <- 4
it <- 1500
```

# Eigenvalues of a Erdos-Renyi Matrix

```{r}
# Get initial stack for p = 0.9
stack <- evl_erdos(M, 0.99, it)
# Iteratively stack various probabilities
stack <- rbind(stack, evl_erdos(M, 0.98, it))
stack <- rbind(stack, evl_erdos(M, 0.95, it))
stack <- rbind(stack, evl_erdos(M, 0.9, it))
stack <- rbind(stack, evl_erdos(M, 0.8, it))
stack <- rbind(stack, evl_erdos(M, 0.7, it))
stack <- rbind(stack, evl_erdos(M, 0.5, it))
stack <- rbind(stack, evl_erdos(M, 0.3, it))
stack <- rbind(stack, evl_erdos(M, 0.1, it))
stack <- rbind(stack, evl_erdos(M, 0.05, it))
stack <- rbind(stack, evl_erdos(M, 0.03, it))
stack <- rbind(stack, evl_erdos(M, 0.01, it))
```

```{r}
eval_scatter <- eval_plot(stack, mat_type = "Erdos-Renyi")
```

```{r}
eval_hist <- ggplot(data = stack) + 
  geom_histogram(mapping = aes(x = Re, fill = as.factor(p_sparsity))) +
  labs(fill = "Sparsity", title = "Real Component of Eigenvalues of ER Matrices")
eval_hist
```

```{r}
#write_csv(stack, "erdos_renyi.csv")
```

```{r}
#eval_scatter
#eval_scatter + transition_states(states = p_sparsity)
```

## Mixed Eigenvalues

```{r}
# Filter eigenvalues with noncomplex components
filtered <- stack[abs(stack[,1]) > 0,]
# Filter eigenvalues with  nonreal components
filtered <- filtered[abs(filtered[,2]) >= 0,]
```

```{r, fig.height = 10}
eval_hist1 <- ggplot(data = filtered) + 
  geom_histogram(mapping = aes(x = Re, fill = as.factor(p_sparsity))) +
  labs(fill = "Sparsity", title = "Real Component of Mixed Eigenvalues of ER Matrices")
eval_hist2 <- ggplot(data = filtered) + 
  geom_histogram(mapping = aes(x = Im, fill = as.factor(p_sparsity))) +
  labs(fill = "Sparsity", title = "Complex Component of Mixed Eigenvalues of ER Matrices")
eval_hist1/eval_hist2
```

## Non-Zero-Real Eigenvalues

```{r}
# Filter eigenvalues with noncomplex components
filtered <- stack[abs(stack[,1]) > 0,]
filtered <- filtered[abs(filtered[,1]) != 1,]
filtered <- filtered[abs(filtered[,2]) != 0,]
```

```{r, fig.height = 10}
eval_hist1 <- ggplot(data = filtered) + 
  geom_histogram(mapping = aes(x = Re, fill = as.factor(p_sparsity))) +
  labs(fill = "Sparsity", title = "Real Component of Nontrivial Eigenvalues")
eval_hist2 <- ggplot(data = filtered) + 
  geom_histogram(mapping = aes(x = Im, fill = as.factor(p_sparsity))) +
  labs(fill = "Sparsity", title = "Complex Component of Nontrivial Eigenvalues")
eval_hist2
```

```{r, cache = T}
real_anim <- eval_hist2 + transition_states(states = p_sparsity, state_length = 0.05, transition_length = 0.05, wrap = FALSE)
#real_anim 
```

```{r}
anim_save(animation = real_anim, filename = "complex_ev.gif")
```

