---
title: "Refactoring matrices.R"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = T, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(matrixcalc)
library(numDeriv)
# Load header
source("../R/header.R")
# Global Parameters
bloud <- F
```

## Symmetric Normal Matrices

```{r}
# Set seed
set.seed(23)
# Set parameters
M <- 8
# Generate matrix
P <- RM_normal(M, normal_args = c(-3,4), symm = F)
Q <- RM_stoch(M, sparsity = T)
if(bloud){P}
```

```{r}
# Set parameters
B <- 1000
steps <- 5
# Evolve batch
evolved_batch_P <- run_batch(P, B, steps, lambda = 10)
evolved_batch_Q <- run_batch(Q, B, steps, lambda = 10)
```

```{r}
eigen_frame(P)
```


```{r}
# Find final elements
last_P <- time_array(evolved_batch_P, at_time = steps)
EV_P <- last_P[,(M+2):ncol(last_P)]
```

```{r}
# Find final elements
last_Q <- time_array(evolved_batch_Q, at_time = steps)
EV_Q <- last_Q[,(M+2):ncol(last_Q)]
```

