---
title: "Random Matrix Analysis"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "R/matrices.R")
source(file = "R/eigenvectors.R")
source(file = "R/eigenmetrics.R")
```

```{r, echo = F}
bool_plot <- T
bool_loud <- F
```

```{r longrun}
evolve <- function(pi, P, steps){
  steps <- it
  # simulate and record evolution of pi
  vals <- matrix(rep(NA, (M+1) * it), ncol = (M+1))
  # rename the columns
  str_vec <- rep(NA, M)
  for(i in 1:M){str_vec[i] = paste("x",i,sep="")}
  colnames(vals) <- c("n",str_vec)
  # evolve pi 
  for(i in 1:it){
    vals[i, ] = c(i, pi %*% matrix.power(P,i))
  }
  #store the values in a dataframe
  vals_ <- data.frame(vals) # store indices as base df in case they are needed
  vals <- subset(vals_, select = -c(n))
  rbind(pi,vals)
}
```

```{r euclidean_plot}
distance <- function(pi,ref_dist){
  #plot difference from a reference/stationary distribution
  diff <- rbind(evolve(pi),ref_dist)
  dist_vec <- rep(0, it)
  for(i in 1:it){
    curr_dist <- stats::dist(diff[c(i,it+1),], method = "euclidean")
    dist_vec[i] <- curr_dist
  }
  data.frame(dist_vec)
}
plot_d <- function(init,ref){
  dist_vec <- distance(init,ref)
  dist_plot <- ggplot(dist_vec, mapping = aes(x = 1:it, y = dist_vec)) + 
    geom_point(color = col_str) + geom_line(color = col_str) +
    labs(x = "n", y = "Euclidean Distance")
  dist_plot
}
```

## Stochastic Matrices

```{r setup_convg}
M <- 4 
P <- RM_symm_stoch(M, r_zeros)
eigen_vecs <- data.frame(eigen(P)[2])
st <- eigen_vecs[1,] # choose reference vector to find distance from
it <- 30 # number of iterations of transition matrix
```

```{r, fig.height = 10}
#set.seed(23)
pi <- r_zeros(M)
evol <- evolve(pi, P, steps = 10)
#dist_vec <- distance(init,st)
```

```{r}
ggplot(evol) + 
  geom_point(mapping = aes(x = x1, y = x2), color = "red") + 
  geom_point(mapping = aes(x = x1, y = x3), color = "blue") +
  geom_point(mapping = aes(x = x1, y = x4), color = "green")
```


