---
title: "Random Matrix Analysis"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "R/matrices.R")
source(file = "R/eigenvectors.R")
source(file = "R/eigenmetrics.R")
```

```{r, echo = F}
bool_plot <- T
bool_loud <- F
M <- 10
```

## Stochastic Matrices

```{r, cache=T}
set.seed(23)
P <- RM_stoch(M, row_fn = r_zeros)
if(bool_plot){eigen_plot(P, loud = bool_loud, "Stochastic")}
```

\newpage

## Symmetric Stochastic Matrices

```{r, cache=T}
set.seed(23)
P <- RM_symm_stoch(M, row_fn = r_zeros)
if(bool_plot){eigen_plot(P, loud = bool_loud, "Symmetric Stochastic")}
```

\newpage

## Normal Symmetric Matrices

```{r, cache=T}
set.seed(23)
P <- RM_symm_norm(M, mu = 0, sd = 1)
if(bool_plot){eigen_plot(P, loud = bool_loud, "Normal Symmetric")}
```

\newpage

## Tridiagonal Matrices

```{r, cache=T}
set.seed(23)
P <- RM_trid(M)
P
if(bool_plot){eigen_plot(P, loud = bool_loud, "Tridiagonal")}
```

