---
title: "Generalizing the Beta Ensembles with Tridiagonal Matrices"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(matrixcalc)
library(ggforce)
# Load files
source(file = "../R/header.R")
.src(depth = 1)
# global parameters
bool_plot <- F
bool_loud <- F
bool_animate <- F
devtools::install_github(repo = "ataqi23/RMAT")
```

```{r}
set.seed(23)
RM_norm(N = 2, cplx = T, herm = T)
```


```{r}
# Set seed
set.seed(23)
# Parameters
size <- 5
N <- 5
beta <- 100
complex <- F
# Ensemble spectrum
ensemble <- RM_ensemble(RM_beta, args = list(N, beta, complex), size = 1000)
ens_spectrum <- ensemble_spectrum(ensemble = ensemble)
spectrum_plot(ens_spectrum)
```


```{r}
# Set seed
set.seed(23)
ensemble <- RM_ensemble(RM_normal, args = list(n = 100, mean = 0, sd = 1, symm = F, complex = T, hermitian = F), size = 50)
ens_spectrum <- ensemble_spectrum(ensemble = ensemble)
spectrum_plot(ens_spectrum)
```

```{r}
# Set seed
set.seed(23)
ensemble <- RM_ensemble(RM_normal, args = list(n = 100, mean = 0, sd = 1, symm = F, complex = T, hermitian = T), size = 50)
ens_spectrum <- ensemble_spectrum(ensemble = ensemble)
spectrum_plot(ens_spectrum)
```


```{r}
GEB_spectrum <- function(N, beta, complex, size){
  spec <- ensemble_spectrum(ensemble = RM_ensemble(RM_beta, args = list(N, beta, complex), size))
  spectrum_plot(spec)
}
# Set seed
set.seed(23)
GEB_spectrum(N = 100, beta = 4, complex = F, size = 100)
```

```{r}
GEB_spectrum(N = 100, beta = 4, complex = T, size = 100)
```


