---
title: "Developer"
author: "Taqi"
date: "3/9/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../R/header.R")
.src(1)
```

```{r}
# Get the master summary "eigen-plot" for a matrix or ensemble
spectral_plots <- function(array, pair_scheme = "largest", disp_metric = "diff_abs", retArrays = F){
  spectrum_array <- spectrum(array)
  dispersion_array <- dispersion(array, pairs = pair_scheme)
  spectrum_scatter <- spectrum_array %>% spectrum.scatterplot()
  dispersion_hist <- dispersion_array %>% dispersion.histogram(metric = disp_metric)
  dispersion_scatter <- dispersion_array %>% dispersion.scatterplot()
  if(retArrays){list(spectrum_scatter,dispersion_hist,dispersion_scatter,spectrum_array,dispersion_array)}
  else{list(spectrum_scatter,dispersion_hist,dispersion_scatter)}
}
```

```{r}
# Simulate P and look at statistics
P <- RME_beta(10, beta = 4, size = 10000)
#P %>% dispersion()
P %>% spectrum.histogram()
# Get plots
spectral_plots(P, disp_metric = "abs_diff")
```

```{r}
# Simulate P and look at statistics
P <- RME_beta(25, beta = 4, size = 100)
P %>% dispersion()
P %>% spectrum.histogram()
# Get plots
spectral_plots(P, disp_metric = "abs_diff")
```

