---
title: "Eigenvectors of Symmetric Matrices"
author: "Ali Taqi"
date: "11/4/2020"
output: pdf_document
header-includes:
  - \newcommand{\R}{\mathbb{R}}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "symm_evc.R")
source(file = "../../R/eigenmetrics.R")
source(file = "../../R/eigen_legacy.R")
#source(file = "../../../R/eigen.R")
source(file = "../../../R/matrices.R")
# Global params
bloud <- F
```

```{r}
S <- RM_symm(8,0.5,10)
#prop <- prop_real_rows(evec_frame(S))
#prop
#avgprop_real_components(evec_frame(S))
```

# Simulation

```{r}
# Params
M <- 200
ep <- 100
d <- ep
# Simulate
f <- 0.5
table <- simulate_by_f_PROP(f = f, M_max = M, ep = ep, draws = d)
head(table)
```

```{r}
model <- glm(formula = prop_vec ~ I(1/M), data = table)
if(bloud)summary(model)
# get coefs
pred <- function(M){
  b0 <- model$coefficients[1]
  b1 <- model$coefficients[2]
  b0 + b1/M
}
# plot
plot_M(table, f) + stat_function(mapping = aes(x = M), fun = pred, color = "red")
```



