---
title: "Eigenvectors of Symmetric Matrices"
author: "Ali Taqi"
date: "11/4/2020"
output: pdf_document
header-includes:
  - \newcommand{\R}{\mathbb{R}}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "symm_evc.R")
source(file = "../../R/eigenmetrics.R")
source(file = "../../R/eigen_legacy.R")
#source(file = "../../../R/eigen.R")
source(file = "../../../R/matrices.R")
```

```{r}
S <- RM_symm(8,0.5,10)
#prop <- prop_real_rows(eigen_frame = evec_frame(S))
#prop
#avgprop_real_components(evec_frame(S))
```

\newpage

# Simulation

```{r}
M <- 15
ep <- 100
d <- ep
```

```{r, cache = T}
f <- 0.5
table <- simulate_by_f_PROP2(f = f, M_max = M, ep_max = ep, draws = d)
head(table)
props_M_ep(table, f = f)
```

```{r, cache = T}
f <- 0.1
#table <- simulate_by_f_PROP2(f = f, M_max = M, ep_max = ep, draws = d)
#head(table)
#props_M_ep(table, f = f)
```

```{r, cache = T}
f <- 0.9
#table <- simulate_by_f_PROP2(f = f, M_max = M, ep_max = ep, draws = d)
#head(table)
#props_M_ep(table, f = f)
```


