---
title: "Ensemble Spectrum Testing"
author: "Ali Taqi"
date: "2/5/2021"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(matrixcalc)
# Load files
source(file = "../R/matrices.R")
source(file = "../R/eigen.R")
source(file = "../R/simulate.R")
source(file = "../R/analyze.R")
source(file = "../R/ensemble.R")
source(file = "../R/vis.R")
# global parameters
bool_plot <- T
bool_loud <- T
bool_animate <- F
```

```{r}
# Create an simulate an ensemble of random matrices
args <- list(M = 4, mean = 0, sd = 1, symm = T)
ensemble <- RM_ensemble(RM_normal, args, size = 50)
# Run the ensemble for a single batch! Need to write new function in simulate.R for ensemble simulations specifically!
#ensemble_sim <- mixtime_ensemble(ensemble, batch_size = 50, steps = 50) 
#batch <- glue_arrays(ensemble_sim, array_index = 1)
#evol_array <- glue_arrays(ensemble_sim, array_index = 2)
batch <- read_csv("batch.csv")
evol_array <- read_csv("evol_array.csv")
```

```{r}
#write_csv(batch,"batch.csv")
#write_csv(evol_array,"evol_array.csv")
```


```{r}
ggplot(data = batch) + 
  geom_histogram(mapping = aes(x = mixtime, fill = eigen_index), bins = 50) + 
  labs(title = "Mixing Time Distribution for a Symmetric Normal Matrix", y = "")
```

```{r}
ratios <- evol_array$r_x2
ratios <- ratios[!is.na(ratios)]
ratios <- data.frame(r_x2 = ratios[which(abs(ratios) < 30)])
```


```{r}
ggplot() + geom_histogram(data = ratios, mapping = aes(x = r_x2), bins = 100)
```


```{r}
batch_ <- batch %>% mutate(inv_mixtime = 1/mixtime)
batch_$mat_idx <- as.factor(batch_$mat_idx)
batch_$eigen_index <- as.factor(batch_$eigen_index)
ggplot() + geom_point(data = batch_, mapping = aes(y = x1, x = inv_mixtime, color = eigen_index))
```


