---
title: "Computational Eigenvector Simulation"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(patchwork)
library(matrixcalc)
library(gganimate)
# Load files
source("../../R/header.R")
.src(2)
```

```{r, echo = F}
# global parameters
bool_plot <- T
bool_loud <- F
bool_animate <- F
```

# Example: A Symmetric Stochastic Matrix

```{r, echo = T, cache = T}

################################
### Step 0: Setup the matrix ###
################################

# Set seed
set.seed(23)
# Set parameters
M <- 4
# Generate matrix
P <- RM_stoch(M, symm = T, sparsity = F)
if(bool_loud){P}

##################################
#### Step 1: Evolve the batch ####
##################################

# Set evolution parameters
B <- 100
steps <- 10
# Evolve batch
sim <- sim_mixtime(P, B, steps)
batch <- sim[[1]]
evolved_batch <- sim[[2]]
if(bool_loud){head(evolved_batch)}

####################################
#### Step 2: Animate the batch! ####
####################################

# Plot the evolution arrays of the batch elements
batch_data1 <- evolved_batch
batch_scatterplot1 <- .batch_2d_plot(batch_data1)

# Add transition time
batch_animation1 <- batch_scatterplot1 + transition_time(time = time)

# Set me to true!
bool_animate <- F
if(bool_animate){batch_animation1}
```

```{r}
# Step 5: Save the animation!
#anim_save(animation = batch_animation1, "stochastic.gif")
#batch_2d_customplot(batch_data = time_array(batch_data1, at_time = 0), 1,2)
```


# Example 2: Normal Matrix

```{r, echo = T, cache = T}

################################
### Step 0: Setup the matrix ###
################################

# Set seed
set.seed(23)
# Set parameters
N <- 3
# Generate matrix
P <- RM_norm(N)
if(bool_loud){P}

##################################
#### Step 1: Evolve the batch ####
##################################

# Set evolution parameters
B <- 100
steps <- 10
# Evolve batch
sim <- sim_mixtime(P, B, steps)
batch <- sim[[1]]
evolved_batch <- sim[[2]]
if(bool_loud){head(evolved_batch)}

# Get the final evolved batch elements after all steps
fully_evolved <- by.time(evolved_batch, at_time = steps)
fully_evolved

####################################
#### Step 2: Animate the batch! ####
####################################

# Plot the evolution arrays of the batch elements
batch_data2 <- evolved_batch
# Pairwise scatter plots
plot_12 <- .batch_2d_customplot(batch_data2, 1, 2)
batch_animation2_1 <- plot_12 + transition_time(time = time)

plot_23 <- .batch_2d_customplot(batch_data2, 2, 3)
batch_animation2_2 <- plot_23 + transition_time(time = time)

plot_13 <- .batch_2d_customplot(batch_data2, 1, 3)
batch_animation2_3 <- plot_13 + transition_time(time = time)
```

```{r}
# Set me to true!
bool_animate1 <- F
if(bool_animate1){batch_animation2_1}
```

```{r}
# Set me to true!
bool_animate2 <- F
if(bool_animate2){batch_animation2_2}
```

```{r}
# Set me to true!
bool_animate3 <- F
if(bool_animate3){batch_animation2_3}
```


