---
title: "Computational Simulation of the Eigenvalues of a Stochastic Matrix"
author: "Ali Taqi"
output: pdf_document
#  includes: 
#    in_header: preamble.tex
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(matrixcalc)
# Load files
source(file = "../../R/header.R")
.src(depth = 2)
```

```{r, echo = F}
# global parameters
bool_plot <- T
bool_loud <- T
bool_animate <- F
```

# Eigenvalues of a Normal Matrix

```{r}
set.seed(23)
P <- RM_norm(4, symm = T)
sim <- sim_mixtime(P, batch_size = 1000, steps = 20)
batch <- sim[[1]]
evolved_batch <- sim[[2]]
```

```{r}
eigen(P)$values
```

```{r}
final <- by.time(evolved_batch, at_time = 20)
final
```

```{r}
ratios <- evolved_batch[,5:10]
```

```{r}
ggplot() + geom_point(data=ratios, aes(x=time, y= r_x1, color = element_index))
ggplot() + geom_point(data=ratios, aes(x=time, y= r_x2, color = element_index))
ggplot() + geom_point(data=ratios, aes(x=time, y= r_x3, color = element_index))
ggplot() + geom_point(data=ratios, aes(x=time, y= r_x4, color = element_index))
```

```{r}
ggplot() + geom_histogram(data=ratios, aes(x= r_x1, fill = time)) +xlim(c(-13,13)) + geom_vline(xintercept = 2.66059061)
ggplot() + geom_histogram(data=ratios, aes(x= r_x2, fill = time)) +xlim(c(-13,13))
ggplot() + geom_histogram(data=ratios, aes(x= r_x3, fill = time)) +xlim(c(-13,13))
ggplot() + geom_histogram(data=ratios, aes(x= r_x4, fill = time)) +xlim(c(-13,13))
```






