---
title: "Computational Eigenvector Simulation"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "R/matrices.R")
source(file = "R/eigenvectors.R")
source(file = "R/simulate.R")
```

```{r, echo = F}
# global parameters
bplot <- F
loud <- F
```

```{r, echo = T}
# Set seed
set.seed(23)
symm <- T
# Set parameters
M <- 3
mu <- 0
sd <- 1
# Generate matrix
P_stoch <- RM_stoch(M, symm, sparsity = F)
P_normal <- RM_normal(M, c(mu,sd), symm)
P <- P_stoch
```

```{r}
if(loud){eigen_frame(P)}
```

```{r, echo = T}
set.seed(23)
# Set batch parameters
B <- 100
# Create batch
batch <- make_batch(M = M, B = B)
# Set evolution parameters
steps <- 5
# Evolve batch
evolved_batch <- evolve_batch(batch, steps, burn_in = 2)
# Add indexing to the batch
evolved_batch <- indexed_batch(evolved_batch, steps)
```

```{r, fig.align = "center", fig.height= 7.5}
#batch_2d_plot(evolved_batch)
plot_empty <- ggplot() 
plot_12 <- batch_2d_customplot(evolved_batch, 1, 2)
plot_23 <- batch_2d_customplot(evolved_batch, 2, 3)
plot_13 <- batch_2d_customplot(evolved_batch, 1, 3)
grid.arrange(plot_empty,plot_12,plot_23,plot_13, ncol = 2)
```

