---
title: "Computational Eigenvector Simulation"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "R/matrices.R")
source(file = "R/eigenvectors.R")
source(file = "R/simulate.R")
```

```{r, echo = F}
# global parameters
bool_plot <- T
bool_loud <- F
```

## Step 0: Setup the matrix

```{r, echo = T}
# Set seed
set.seed(23)
# Set parameters
M <- 2
mu <- 0
sd <- 1
# Generate matrix
P <- RM_stoch(M, symm = T, sparsity = F)
```

```{r}
eigen_frame(P)
```


## Step 1: Get the batch 

```{r}
# Set batch parameters
B <- 100
# Create batch
batch <- make_batch(M = M, B = B)
head(batch)
```


## Step 2: Evolve the batch

```{r}
# Set evolution parameters
steps <- 20
# Evolve batch
evolved_batch <- evolve_batch(batch, steps)
# Add indexing to the batch
evolved_batch <- indexed_batch(evolved_batch, steps)
head(evolved_batch)
tail(evolved_batch)
```

\newpage

## Step 3: Analyze the batch

```{r}
# Plot the evolution arrays of the batch elements
batch_data <- evolved_batch
# 2d plot
batch_2d_plot(batch_data, "(Symmetric Stochastic Matrix)")
```



