---
title: 'Mixing Times of Stochastic Matrices'
author: "Ali Taqi"
date: "2/15/2021"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.align = "center", fig.height = 4)
# Load libraries
library(tidyverse)
library(matrixcalc)
library(patchwork)
# Load files
source(file = "../../R/header.R")
.src(depth = 2)
# Global parameters
bool_plot <- T
bool_loud <- F
```

```{r}
# Global simulation parameters
batch_size <- 250
```


## Stochastic Matrix Mixing Time

```{r, echo = F}
set.seed(23)
# Generate a stochastic matrix
P <- RM_stoch(N = 4, symm = T)
P
```

### Epsilon = 0.01

```{r}
# Evolve a batch
sim <- sim_mixtime(P, batch_size, steps = 11, epsilon = 0.01)
# Extract the arrays
batch <- sim[[1]]
evolved_batch <- sim[[2]]
if(bool_loud){head(batch)}
mixtime_histogram(batch, mat = "Stochastic ")
.prop_mixed(batch)
```

### Epsilon = 0.02

```{r}
# Evolve a batch
sim <- sim_mixtime(P, batch_size, steps = 11, epsilon = 0.02)
# Extract the arrays
batch <- sim[[1]]
evolved_batch <- sim[[2]]
mixtime_histogram(batch, mat = "Stochastic ")
.prop_mixed(batch)
```

### Epsilon = 0.05

```{r}
# Evolve a batch
sim <- sim_mixtime(P, batch_size, steps = 11, epsilon = 0.05)
# Extract the arrays
batch <- sim[[1]]
evolved_batch <- sim[[2]]
mixtime_histogram(batch, mat = "Stochastic ")
.prop_mixed(batch)
```

### Epsilon = 0.1

```{r}
# Evolve a batch
sim <- sim_mixtime(P, batch_size, steps = 11, epsilon = 0.1)
# Extract the arrays
batch <- sim[[1]]
evolved_batch <- sim[[2]]
mixtime_histogram(batch, mat = "Stochastic ")
.prop_mixed(batch)
```

### Epsilon = 0.2

```{r}
# Evolve a batch
sim <- sim_mixtime(P, batch_size, steps = 11, epsilon = 0.2)
# Extract the arrays
batch <- sim[[1]]
evolved_batch <- sim[[2]]
mixtime_histogram(batch, mat = "Stochastic ")
.prop_mixed(batch)
```
