---
title: 'Mixing Times of Erdos-Renyi Walks'
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.align = "center", fig.height = 4)
# Load libraries
library(tidyverse)
library(matrixcalc)
library(patchwork)
# Load files
source(file = "../../R/header.R")
.src(depth = 2)
# Global parameters
bool_plot <- T
bool_loud <- F
```

```{r}
# Document simulation parameters
N <- 10
batch_size <- 500
steps <- 8
epsilon <- 0.015
```


# Erdos-Renyi Walk Mixing Times

```{r}
set.seed(23)
p <- 0.4
# Generate a stochastic matrix
P <- RM_erdos(N, p, stoch = T)
P
# Evolve a batch
sim <- sim_mixtime(P, batch_size, steps, epsilon)
# Extract the arrays
batch <- sim[[1]]
evolved_batch <- sim[[2]]
if(bool_loud){head(batch)}
mixtime_histogram(batch, mat = paste("Erdos-",p," ",sep=""))
.prop_mixed(batch)
```

\newpage

```{r}
set.seed(23)
# Generate a stochastic matrix
P <- RM_erdos(n = n, p_sparse = 0.5, stoch = T)
P
# Evolve a batch
sim <- mixtime_sim(P, batch_size, steps, epsilon)
# Extract the arrays
batch <- sim[[1]]
evolved_batch <- sim[[2]]
if(bool_loud){head(batch)}
mixtime_histogram(batch, mat = "Erdos-0.5 ")
prop_mixed(batch)
```

\newpage

```{r}
set.seed(23)
# Generate a stochastic matrix
P <- RM_erdos(n = n, p_sparse = 0.2, stoch = T)
P
# Evolve a batch
sim <- mixtime_sim(P, batch_size, steps, epsilon)
# Extract the arrays
batch <- sim[[1]]
evolved_batch <- sim[[2]]
if(bool_loud){head(batch)}
mixtime_histogram(batch, mat = "Erdos-0.2 ")
prop_mixed(batch)
```
