---
title: "Random Matrix Analysis"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "../R/matrices.R")
source(file = "R/eigenvectors.R")
source(file = "R/eigenmetrics.R")
```

```{r}
bool_plot <- T
bool_loud <- F
M <- 20
```

# Eigenmetrics of Various Random Matrices

## Stochastic Matrix

```{r, cache=T}
P <- RM_stoch(M, sparsity = T)
if(bool_plot){eigen_plot(P, loud = bool_loud, "Stochastic")}
eigen_summary(eigen_frame(P))
```

```{r, echo = F, fig.height = 6, fig.height = 4}
L_eigenplot(P)
R_eigenplot(P)
```

\newpage

## Symmetric Stochastic Matrix

```{r, cache=T}
set.seed(23)
P <- RM_stoch(M, symm = T, sparsity = T)
if(bool_plot){eigen_plot(P, loud = bool_loud, "Symmetric Stochastic")}
eigen_summary(eigen_frame(P))
```

```{r, echo = F, fig.height = 6, fig.height = 4}
L_eigenplot(P)
R_eigenplot(P)
```

\newpage

## Normal Symmetric Matrix

```{r, cache=T}
set.seed(23)
P <- RM_normal(M, symm = T)
if(bool_plot){eigen_plot(P, loud = bool_loud, "Normal Symmetric (Mu = 0)")}
eigen_summary(eigen_frame(P))
```

```{r, echo = F, fig.height = 6, fig.height = 4}
L_eigenplot(P)
R_eigenplot(P)
```

\newpage

## Normal Symmetric Matrix

```{r, cache=T}
set.seed(23)
P <- RM_normal(M, normal_args = c(1,2), symm = T)
if(bool_plot){eigen_plot(P, loud = bool_loud, "Normal Symmetric (Mu = 1)")}
eigen_summary(eigen_frame(P))
```

```{r, echo = F, fig.height = 6, fig.height = 4}
L_eigenplot(P)
R_eigenplot(P)
```

\newpage

## Tridiagonal Matrix

```{r, cache=T}
set.seed(23)
P <- RM_trid(M)
if(bool_plot){eigen_plot(P, loud = bool_loud, "Tridiagonal")}
eigen_summary(eigen_frame(P))
```

```{r, echo = F, fig.height = 6, fig.height = 4}
L_eigenplot(P)
R_eigenplot(P)
```


