---
title: "Sparsity Analysis"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE, fig.height = 2.6)
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
library(latex2exp)
# Load files
source(file = "../R/matrices.R")
source(file = "../R/eigenvectors.R")
source(file = "../R/eigenmetrics.R")
# Global parameters
col_str <- "blue"
bsummary <- T
bloud <- F
bplot <- T
```

# Demonstration

```{r sparsity, echo = T, fig.height = 4}
# Set parameters
M <- 6
p <- 0.5
# Generate matrix (Erdos-Renyi)
P <- RM_erdos(M, p) 
# Get eigenvalues
eigen_df <- eigen_frame(P)
eigen_plot(P,mat_type = "Erdos-Renyi")
```

\newpage

# Various Parameter Values

```{r parameters}
M_vec <- c(3,5,10)
p_vec <- c(0.1,0.5,0.8)
c(M1,M2,M3) %<-% M_vec
c(p1,p2,p3) %<-% p_vec
P_vec1 <- matrix(c(RM_erdos(M1,p1),
                  RM_erdos(M1,p1),
                  RM_erdos(M1,p1)),
                nrow = M_vec[1])
P_vec2 <- matrix(c(RM_erdos(M2,p2),
                  RM_erdos(M2,p2),
                  RM_erdos(M2,p2)),
                nrow = M_vec[2])
P_vec3 <- matrix(c(RM_erdos(M3,p3),
                  RM_erdos(M3,p3),
                  RM_erdos(M3,p3)),
                nrow = M_vec[3])
```

\newpage 

## Erdos-Renyi Matrices (M = 3)

```{r, echo = FALSE}
P <- P_vec1[,1:M1 + 0*M1]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[1],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```

```{r, echo = FALSE}
P <- P_vec1[,1:M1 + 1*M1]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[2],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```

```{r, echo = FALSE}
P <- P_vec1[,1:M1 + 2*M1]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[3],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```

\newpage

## Erdos-Renyi Matrices (M = 5)

```{r, echo = FALSE}
P <- P_vec2[,1:M2 + 0*M2]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[1],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```

```{r, echo = FALSE}
P <- P_vec2[,1:M2 + 1*M2]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[2],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```


```{r, echo = FALSE}
P <- P_vec2[,1:M2 + 2*M2]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[3],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```

\newpage

## Erdos-Renyi Matrices (M = 10)

```{r, echo = FALSE}
P <- P_vec3[,1:M3 + 0*M3]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[1],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```

```{r, echo = FALSE}
P <- P_vec3[,1:M3 + 1*M3]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[2],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```

```{r, echo = FALSE}
P <- P_vec3[,1:M3 + 1*M3]
if(bplot){eigen_plot(P, loud = F, mat_type = paste(p_vec[3],"-Sparse",sep=""))}
if(bsummary){eigen_summary(eigen_frame(P))}
```

\newpage
