---
output: pdf_document
header-includes:
  - \newcommand{\R}{\mathbb{R}}
---

## 2-dimensional Symmetric Matrix

Take an arbitrary two dimensional symmetric matrix:

\[
  {S}_{2} =
  \begin{pmatrix}
    d_1&a\\
    a&d_2\\
  \end{pmatrix},
  \]
  
$\textbf{Notation.}$ Let $\alpha_i(\lambda) = (d_i - \lambda)$.

We obtain the determinant of $(S_2 - \lambda I)$ to be:

$$\det{(S_2 - \lambda I)} = \alpha_1\alpha_2 - a^2$$
So to solve for the roots of our characteristic polynomial, we set $\det{(S_2 - \lambda I)} = 0$ and get the equation:

$$\alpha_1(\lambda)\cdot \alpha_2(\lambda) = a^2$$
If $a$ were to be real, then we would expect ${\alpha_1 \alpha_2} \geq 0$, since otherwise, the square root would be imaginary. So we obtain some useful conditions by solving the inequality:

$S_2$ is real when any of the following is true:

(1) $\alpha_1,\alpha_2 \in \R^{-} \iff (d_1 > \lambda) \space \wedge \space (d_2 > \lambda)$
(2) $\alpha_1 = 0$ or $\alpha_2 = 0 \iff (d_1 = \lambda) \vee (d_2 = \lambda)$
(3) $\alpha_1,\alpha_2 \in \R^{+} \iff (d_1 < \lambda) \space \wedge \space (d_2 < \lambda)$

\newpage

## 3-dimensional Symmetric Matrix

Take an arbitrary three dimensional symmetric matrix:

\[
  {S}_{3} =
  \begin{pmatrix}
    d_1&a&b\\
    a&d_2&c\\
    b&c&d_3\\
  \end{pmatrix},
  \]

We obtain the determinant of $(S_3 - \lambda I)$ to be:
$$\det{(S_2 - \lambda I)} = \alpha_1\alpha_2\alpha_3 - \alpha_1c^2 - \alpha_2b^2 - \alpha_3a^2 + 2abc$$

So solving for $\det{(S_2 - \lambda I)} = 0$ yields:
$$\alpha_1\alpha_2\alpha_3 - \alpha_1c^2 - \alpha_2b^2 - \alpha_3a^2 + 2abc = 0$$

If we consolidate the left hand side into one function of our free parameters, we obtain:
$$f(d_1,d_2,d_3,a,b,c,\lambda) = 0$$

## Generalization

Suppose we have an arbitrary m-dimensional symmetric matrix, call it $S_m$.

Then, we obtain that the solution to the roots of the characteristic polynomial is $\det{(S_m - \lambda I)} = 0$. We may find that the number of free parameters is $m$ diagonal entries, and $T(m) = \frac{m(m+1)}{2}$ non-diagonal (triangular) entries and $\lambda$. So solving for the eigenvalues of a symmetric matrix yields:
$$f(d_1,\dots,d_m, a_1,\dots,a_{T(m)},\lambda) = 0$$