---
author: "Ali Taqi"
output: pdf_document
header-includes:
  - \usepackage{physics}
  - \newcommand{\bi}{\begin{itemize}}
  - \newcommand{\ei}{\end{itemize}}
  - \newcommand{\dfn}{\textbf{(Definition)} \,}
  - \newcommand{\thm}{\textbf{(Theorem)} \,}
  - \newcommand{\lma}{\textbf{(Lemma)} \,}
  - \newcommand{\Prb}{\text{P}}
  - \newcommand{\R}{\mathbb{R}}
  - \newcommand{\N}{\mathbb{N}}
  - \newcommand{\M}{\mathcal{M}}
  - \newcommand{\st}{\, | \,}
  - \newcommand{\seqX}{X_0,X_1,\dots,X_n}
---

# Chapter 2

## Random Matrices

$\dfn \textbf{Random Matrix.}$ Suppose we have an arbitrary matrix, $P \in \M_\R[M,N]$ for some $M,N \in \N^+$. Then, we call $P$ a random matrix is all of its entries $p_{ij}$ are random variables.

$\dfn \textbf{Ergodic Matrix.}$ A matrix is ergodic if it is aperiodic, and positive irreducible.

## Ergodicity


\begin{itemize}
\item .
\end{itemize}

# Notation

Suppose we have a $M \times M$ square matrix $\bf P$ (for some $M \in \mathbb{N}$) on a field $F$. We notate $\mathbf{P} \in \mathcal{M}_F[M^2]$.

Take $\mathbf{P} \in \mathcal{M}_F[M^2]$.

## Structural Properties of Matrices

If $\bf P$ is symmetric, then its upper triangle is equal to the lower triangle.

If $\bf P$ is tridiagonal, then it is a band matrix of width 1.

\bigskip

## Entry-wise Properties of Matrices

If $\bf P$ is row-stochastic, then $\forall i : \sum_j p_{ij} = 1$.

`RM_stoch <- function(M, symm = F, sparsity = F){...}`

\medskip

If $\bf P$ is $\mathcal{N}(\mu,\sigma^2)$, then its entries satisfy $p_{ij} \sim \mathcal{N}(\mu,\sigma^2)$.

`RM_normal <- function(M, normal_args = c(0,1), symm = F){...}`

\medskip

If $\bf P$ is $p-\text{sparse}$, then $\forall i, j \in S_M : p_{ij}/c \sim \text{Bern}(p)$ for some $c \in \mathbb{R}$.

`RM_erdos <- function(M, p_sparse){...}` 
