---
title: "Chapter 2 Graphics"
author: "Taqi"
#date: "4/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("../R/header.R")
library(future)
library(wesanderson)
.src(1)
```

```{r}
wes_pal <- wes_palette("Zissou1", 100, type = "continuous")
```


```{r, eval = FALSE, include = FALSE}
set.seed(23)
run <- F
if(run){
  save <- T
  if(save){
    ggsave(filename = "test.pdf", path = "chap2", width = 10.5, height = 7)
  }
}
```

# Section 2

# Order Statistics 1

```{r}
# ===================================================
#                       Setup
# ===================================================
extreme_norms_plot <- function(ens_spec, N){
  # Partition dataset
  order_1 <- ens_spec %>% filter(Order == 1)
  order_2 <- ens_spec %>% filter(Order == 2)
  order_3 <- ens_spec %>% filter(Order == 3)
  order_N2 <- ens_spec %>% filter(Order == N-2)
  order_N1 <- ens_spec %>% filter(Order == N-1)
  order_N <- ens_spec %>% filter(Order == N)
  # Plot
  ens_spec %>%
    mutate(Order = fct_relevel(.f = c("1","2","3","18","19","20"))) %>%
    ggplot() +
    geom_histogram(data = order_1,  mapping = aes(x = Norm, fill = "1"), alpha = alpha, bins = bins) +
    geom_histogram(data = order_2,  mapping = aes(x = Norm, fill = "2"), alpha = alpha, bins = bins) +
    geom_histogram(data = order_3,  mapping = aes(x = Norm, fill = "3"), alpha = alpha, bins = bins) +
    geom_histogram(data = order_N2, mapping = aes(x = Norm, fill = paste(N-2)), alpha = alpha, bins = bins) +
    geom_histogram(data = order_N1, mapping = aes(x = Norm, fill = paste(N-1)), alpha = alpha, bins = bins) +
    geom_histogram(data = order_N,  mapping = aes(x = Norm, fill = paste(N)), alpha = alpha, bins = bins) +
    scale_fill_brewer(palette = "Spectral")
}
extreme_norms_plotv2 <- function(ens_spec, N){
  ens_spec <- ens_spec %>% mutate(Order = as.factor(Order))
  ens_spec %>% 
    ggplot() +
    geom_histogram(mapping = aes(x = Norm, fill = Order), alpha = alpha, bins = bins) +
    scale_fill_brewer(palette = "Spectral")
}
# ===================================================
#                   Simulation
# ===================================================
set.seed(23)
run <- T
if(run){
  # Set parameters
  N <- 10
  # Generate ensemble
  ens <- RME_norm(N = N, symm = T, size = 500)
  if(T){  
    # Get spectrum 
    ens_spec <- ens %>% spectrum_par(order = 1:N)
    write.csv(ens_spec, "data/spec_order12.csv", row.names = F)
  } else{
    ens_spec <- read_csv("data/spec_order12.csv")
  }
  # Plot parameters
  alpha <- 0.5
  bins <- 70
  # Set function
  if(F){fn <- extreme_norms_plot} else{fn <- extreme_norms_plotv2}
  # Get plot
  ens_plot <- fn(ens_spec, N) +
    labs(fill = "Order", 
         title = paste("Distribution of the Largest Eigenvalues of a", 
                       makeTitle(N, "Symmetric Normal Matrix")))
  ens_plot
  # Save plot
  save <- T
  if(save){
    ggsave(filename = "2-2-1_spec_order12.pdf", path = "chap2", width = 10.5, height = 7)
  }
}
```

## Order Statistics 2

```{r}
set.seed(23)
run <- T
if(run){
  # Set parameters
  N <- 25
  # Generate ensemble
  ens <- RME_norm(N = N, symm = T, size = 750)
  if(T){  
    # Get spectrum 
    ens_spec <- ens %>% spectrum_par(norm_order = FALSE)
    if(F){write.csv(ens_spec, "data/spec_order_density.csv", row.names = F)}
  } else{
    ens_spec <- read_csv("data/spec_order_density.csv")
  }
  # Get plot
  ens_plot <- ens_spec %>%
    ggplot(mapping = aes(x = Norm, group = Order, color = Order)) +
    geom_density(kernel = "gaussian") +
    scale_color_gradientn(colours = wes_pal) + 
      labs(fill = "Order", 
           title = paste("Distribution of the Eigenvalues of a", 
                         makeTitle(N, "Symmetric Normal Matrix by Order")))
  ens_plot
  # Save plot
  save <- T
  if(save){
    ggsave(filename = "2-2-1_spec_order_density.jpg", path = "chap2", width = 10.5, height = 7)
  }
}

```

## Order Statistics 3

```{r}
set.seed(23)
run <- T
if(run){
  # Set parameters
  N <- 50
  # Generate ensemble
  ens <- RME_norm(N = N, symm = T, size = 300)
  if(F){  
    # Get spectrum 
    ens_spec <- ens %>% spectrum_par()
    write.csv(ens_spec, "data/spec_order_density.csv", row.names = F)
  } else{
    ens_spec <- read_csv("data/spec_order_density.csv")
  }
  # Get plot
  ens_plot <- order.summary(ens_spec, Variance_Re)
  ens_plot
  # Save plot
  save <- T
  if(save){
    ggsave(filename = "2-2-1_spec_order_summary.pdf", path = "chap2", width = 10.5, height = 7)
  }
}
```

