---
title: "Code Examples"
author: "Taqi"
date: "4/14/2021"
output: pdf_document
---

```{r, include = F}
source("../R/header.R")
.src(d = 1)
library(tidyverse)
```

# Chapter 3

## Section 1.2

### Consecutive Pairing Scheme

```{r}
pair_indices <- .consecutive_pairs(N = 5)
```

```{r, eval = F}
\begin{lstlisting}[language=R]
# Helper function in the source code
pair_indices <- .consecutive_pairs(N = 5)
# Outputs the following
pair_indices
...
i j
2 1
3 2
4 3
5 4
\end{lstlisting}
```

### Lower Pairing Scheme

```{r}
pair_indices <- .unique_pairs_lower(N = 4)
```

```{r, eval = F}
\begin{lstlisting}[language=R]
# Helper function in the source code
pair_indices <- .unique_pairs_lower(N = 4)
# Outputs the following
pair_indices
...
     i j
[1,] 2 1
[2,] 3 1
[3,] 3 2
[4,] 4 1
[5,] 4 2
[6,] 4 3
\end{lstlisting}
```

## Section 1.3

```{r}
set.seed(23)
P <- RM_norm(N = 5, mean = 0, sd = 1)
disp_P <- dispersion(P, pairs = "consecutive")
# Outputs the following
disp_P
```

```{r, eval = F}
\begin{lstlisting}[language=R]
library(RMAT)
P <- RM_norm(N = 5, mean = 0, sd = 1)
disp_P <- dispersion(P, pairs = "consecutive")
# Outputs the following
disp_P
...
   i j eig_i           eig_j           id_diff        id_diff_norm abs_diff diff_ij
1  2 1 -0.5434-1.3539i -0.5434+1.3539i 0.0000+2.7078i 2.7078       0.0000   1
2  3 2 0.2255+1.4250i -0.5434-1.3539i -0.7689-2.7789i 2.8833       0.0161   1
3  4 3 0.2255-1.4250i 0.2255+1.4250i   0.0000+2.8500i 2.8500       0.0000   1
4  5 4 -0.8678+0.0000i 0.2255-1.4250i  1.0933-1.4250i 1.7961       0.5749   1
\end{lstlisting}
```

### Beta Ensemble Dispersion

```{r}
set.seed(23)
ens <- RME_beta(N = 4, beta = 4, size = 3)
disp_ens <- dispersion(ens, pairs = "consecutive")
# Outputs the following
disp_ens
```

```{r, eval = F}
\begin{lstlisting}[language=R]
library(RMAT)
ens <- RME_beta(N = 4, beta = 4, size = 3)
disp_ens <- dispersion(ens, pairs = "consecutive")
# Outputs the following
disp_ens
...
i j eig_i    eig_j    id_diff iddf_norm abs_diff diff_ij
2 1 -3.78+0i 4.00+0i  7.78+0i 7.78      0.22     1
3 2 2.06+0i -3.78+0i -5.84+0i 5.84      1.72     1
4 3 0.19+0i  2.06+0i  1.88+0i 1.88      1.88     1
2 1 3.80+0i -4.00+0i -7.80+0i 7.80      0.20     1
3 2 -1.80+0i 3.80+0i  5.60+0i 5.60      2.00     1
4 3 0.89+0i -1.80+0i -2.69+0i 2.69      0.92     1
2 1 3.51+0i -3.53+0i -7.04+0i 7.04      0.03     1
3 2 1.35+0i  3.51+0i  2.16+0i 2.16      2.16     1
4 3 -0.67+0i 1.35+0i  2.02+0i 2.02      0.68     1
\end{lstlisting}
```