---
title: "Polished"
author: "Taqi"
#date: "3/9/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(future)
library(viridis)
library(tidyverse)
source("../../R/header.R")
.src(2)
```

```{r}
# Setup parallel compuations 
future::plan(strategy = multisession)
print("Future plan has been set to multisession by default.")
```

```{r}
# Find the eigenvalue dispersions for a given matrix
.dispersion_matrix2 <- function(P, pairs, sort_norms, norm_pow, digits = 4){
  eigenvalues <- spectrum(P, sort_norms = sort_norms) # Get the sorted eigenvalues of the matrix
  norm_fn <- function(x){(abs(x))^norm_pow} # Generate norm function to pass along as argument (Euclidean or Beta norm)
  disp <- purrr::map2_dfr(pairs[,1], pairs[,2], .resolve_dispersion, eigenvalues, norm_fn, digits) # Evaluate the matrix dispersion
  disp$normalized <- disp$id_diff_norm / mean(disp$id_diff_norm)
  disp
}

dispersion2 <- function(array, pairs = NA, sort_norms = T, norm_pow = 1){
  digits <- 4 # Digits to round values to
  pairs <- .parsePairs(pairs, array) # Parse input and generate pair scheme (default NA), passing on array for dimension and array type inference
  # Array is a matrix; call function returning dispersion for singleton matrix
  if(class(array) == "matrix"){.dispersion_matrix2(array, pairs, sort_norms, norm_pow, digits)}
  # Array is an ensemble; recursively row binding each matrix's dispersions
  else if(class(array) == "list"){furrr::future_map_dfr(array, .dispersion_matrix2, pairs, sort_norms, norm_pow, digits)}
}
```

## Wigner's Surmise for Beta Ensembles

```{r}
# Labels a generic array with a value column
.label_array <- function(array, value, label, size){
  label_column <- data.frame(x = rep(value, size))
  colnames(label_column) <- as.factor(label)
  cbind(array, label_column)
}
# Creates a tidy, labelled p-Erdos ensemble spectrum
beta_wigner_dispersion <- function(beta, N, size){
  beta_disp <- RME_beta(N, beta, size) %>% dispersion2(pairs = "consecutive", sort_norms = F)
  beta_disp %>% .label_array(value = beta, label = "beta", size = nrow(beta_disp))
}
```

```{r, echo = T}
# Global parameters
N <- 100
size <- 350
betas <- c(1,2,4)
# Generate the p-ensembles
if(F){beta_wigner <- purrr::map_dfr(betas, beta_wigner_dispersion, N, size)} else{
  beta_wigner <- read.csv("beta-wigner.csv")}
beta_wigner$beta <- as.factor(beta_wigner$beta)
```

```{r}
#write.csv(beta_wigner, "beta-wigner.csv", row.names = F)
```


```{r}
beta_wigner %>% 
  ggplot(aes(x = normalized, group = beta, color = beta)) + 
  geom_density() +
  scale_color_brewer(type = "qual", palette = "Set2")  +
  labs(title = "Wigner's Surmise for the Beta Ensembles")
ggsave(filename = "wigner-beta.pdf")
```

```{r, echo = T}
# Global parameters
N <- 50
size <- 250
betas <- c(1,2,3,4,5,6,7,8,9,10)
# Generate the p-ensembles
if(F){beta_wigner <- purrr::map_dfr(betas, beta_wigner_dispersion, N, size)} else{
  beta_wigner <- read.csv("beta-wigner-extended.csv")
}
beta_wigner$beta <- as.factor(beta_wigner$beta)
```

```{r}
#write.csv(beta_wigner, "beta-wigner-extended.csv", row.names = F)
```

```{r}
beta_wigner %>% 
  ggplot(aes(x = normalized, group = beta, color = beta)) + 
  geom_density() +
  scale_color_brewer(palette = "Spectral") +
  labs(title = "Wigner's Surmise for the Beta Ensembles")
ggsave(filename = "wigner-beta-extended.pdf")
#+
  #scale_color_brewer(type = "qual", palette = "Spectral")
```