---
title: "Mixing Times"
author: "Ali Taqi"
date: "2/5/2021"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(matrixcalc)
# Load files
source(file = "../R/matrices.R")
source(file = "../R/eigen.R")
source(file = "../R/simulate.R")
source(file = "../R/ratios.R")
source(file = "../R/analyze.R")
# global parameters
bool_plot <- F
bool_loud <- T
bool_animate <- F
data <- F
```

# Eigenvalues of a Normal Matrix

```{r}
set.seed(23)
M <- 4
# Generate matrix
P <- RM_normal(M, normal_args = c(0,1), symm = T)
# Run a batch
batch <- make_batch(M, B = 100)
# Evolve a batch
if(!data){evolved_batch <- evolve_batch(P, batch, steps = 30)}
if(data){evolved_batch <- read_csv(file = "../data/stdnormal_4_1000.csv")}
# Get eigenvalues
eigenvalues <- eigen(P)$values
eigenvalues
```


```{r}
# Classify candidate eigenvectors
if(!data){evolved_batch0 <- eigen_classify(evolved_batch, P, epsilon = 0.05)}
if(data){evolved_batch0 <- read_csv(file = "../data/evolved_batch0.csv")}
# Add mixing times to the batch
batch0 <- eigen_mixtime(evolved_batch0,batch)
```

```{r}
hist <-ggplot(data = batch0) + 
  geom_histogram(mapping = aes(x = mixtime), fill = "deepskyblue3") + 
  labs(title = "Mixing Time Distribution for a Symmetric Standard Normal Matrix", y = "")
```

```{r}
plot1 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x1, y = mixtime, color = mixtime))
plot2 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x2, y = mixtime, color = mixtime))
plot3 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x3, y = mixtime, color = mixtime))
plot4 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x4, y = mixtime, color = mixtime))
#grid.arrange(plot1,plot2,plot3,plot4)
if(bool_plot){  
  plot1
  plot2
  plot3
  plot4
}
```

```{r}
plot1 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x1, y = x2, color = mixtime))
plot2 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x2, y = x3, color = mixtime))
plot3 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x3, y = x4, color = mixtime))
plot4 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x4, y = x2, color = mixtime))
plot5 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x4, y = x3, color = mixtime))
plot6 <- ggplot() + geom_point(data = batch0, mapping = aes(x = x4, y = x1, color = mixtime))
if(bool_plot){  
  plot1
  plot2
  plot3
  plot4
  plot5
  plot6
}
```



