---
title: "Ensemble Spectrum Testing"
author: "Ali Taqi"
date: "2/5/2021"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(matrixcalc)
# Load files
source(file = "../R/matrices.R")
source(file = "../R/eigen.R")
source(file = "../R/simulate.R")
source(file = "../R/analyze.R")
source(file = "../R/ensemble.R")
# global parameters
bool_plot <- T
bool_loud <- T
bool_animate <- F
```

```{r}
# Create an simulate an ensemble of random matrices
args <- list(M = 4, mean = 0, sd = 1, symm = T)
ensemble <- RM_ensemble(RM_normal, args, size = 2)
```

```{r}
P <- ensemble[[1]]
simres <- mixtime_sim(P, 5, 5)
#do.call(c, list(P,simres))
whats <- c(list(P), simres)
whats2 <- whats
biglist <- list(whats, whats2)
```


```{r}
mixtime_ensemble <- function(ensemble, batch_size, steps, epsilon = 0.1){
  # Initialize the stack
  ensemble_result <- list(sim_by_element(ensemble, batch_size, steps, epsilon, ensemble_index = 1)) 
  # Go through rest of ensemble
  for(i in 2:length(ensemble)){
    curr_result <- list(sim_by_element(ensemble, batch_size, steps, epsilon, ensemble_index = i)) 
    ensemble_result <- c(ensemble_result, curr_result) # Concatenate results
  }
  ensemble_result
}
```

```{r}
res <- mixtime_ensemble(ensemble, batch_size = 5, steps = 5)
```

