---
title: "Thesis Direction"
author: "Ali Taqi"
date: "2/4/2021"
output: pdf_document
---

Currently, the thesis loosely focuses on "Spectral Statistics of Random Matrices". To narrow down our focus, this document will outline and organize the potential avenues of focus. Listed below are the avenues of spectral statistics to explore.

For a given matrix (ensemble), consider the following spectral statistics:

## Eigenvalue specrtra

1. The actual spectra of the RM(E), under varying free parameters. $(\sigma(P))$
1. The spacings between the eigenvalues, and related statistics. $\{\lambda_i - \lambda_j \mid \lambda_i, \lambda_j \in \sigma(P)\}$
1. Radial density/distribution of the eigenvalues. $P(||\lambda_i|| = r) \text{ for } r \in[0,1]$


## Consecutive Ratio Sequences

1. The distribution of the ratios (and log-ratios) in the CRS. ($\frac{(\alpha_n)_j}{(\alpha_{n-1})_j} \text{ for } j = 1,\dots,M \text{ and } \alpha_k = \vec{a}Q^k$)
1. Variance of the ratios at a given matrix time/power $n$. ($V(n) = \text{Var}\left(\left|\frac{\vec{a}Q^{n+1}}{\vec{a}Q^n}\right|\right)$)

## Mixing Times

1. The mixing time distribution for various matrices under varying free parameters.
