---
title: "Eigenvectors of Symmetric Matrices"
author: "Ali Taqi"
date: "11/4/2020"
output: pdf_document
header-includes:
  - \newcommand{\R}{\mathbb{R}}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
# Load libraries
library(tidyverse)
library(knitr)
library(patchwork)
library(ggfortify)
library(matrixcalc)
library(zeallot)
# Load files
source(file = "symm_evc.R")
source(file = "../../R/eigenmetrics.R")
source(file = "../../R/eigen_legacy.R")
#source(file = "../../../R/eigen.R")
source(file = "../../../R/matrices.R")
```

# Computational Evidence: Real Symmetric Matrices have Real Eigenvectors

```{r}
# Uniform matrix with symm = T
RM_symm(5,0.5,10)
```

# Simulation

```{r, cache = T}
table <- simulate_by_f(f = 0.1, M_max = 15, ep_max = 50, draws = 50)
head(table)
plot_f_table(table, f = 0.1)
```

```{r, cache = T}
#table <- simulate_by_f(f = 0.5, M_max = 15, ep_max = 250, draws = 250)
#head(table)
#plot_f_table(table, f = 0.5)
```

```{r, cache = T}
#table <- simulate_by_f(f = 0.9, M_max = 15, ep_max = 250, draws = 250)
#head(table)
#plot_f_table(table, f = 0.9)
```
