---
title: "Computational Simulation of the Eigenvalues of a Stochastic Matrix"
author: "Ali Taqi"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.align = "center", 
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
library(patchwork)
library(gridExtra)
library(matrixcalc)
library(numDeriv)
# Load files
source(file = "../R/matrices.R")
source(file = "../R/eigen.R")
source(file = "../R/simulate.R")
source(file = "../R/analyze.R")
# global parameters
bool_plot <- T
bool_loud <- T
bool_animate <- F
```

# Eigenvalues of a Symmetric Normal Matrix

```{r, echo = T, cache = T}
# Set seed
set.seed(25)
# Set parameters
M <- 3
# Generate matrix
P <- RM_stoch(M, symm = T)
P
# Run a batch
batch <- make_batch(M = 3, B = 200, lambda = 10, complex = FALSE)
```

```{r}
evolved_batch <- evolve_batch(batch, steps = 70, final_time = TRUE)
head(evolved_batch)
```

```{r}
eigen(P)$values
```

# Numerical Eigenvalue Analysis

## Sorted Eigenvalues

```{r}
eigenbatch <- eigen_crosscheck(evolved_batch, P, 0.2)
d <- ncol(eigenbatch)
head(eigenbatch[,(d-3):d])
```

## Initial Plot

```{r}
# Add eigen_index to initial batch
eigen_index0 <- eigenbatch$eigen_index
batch <- cbind(batch,eigen_index0)
ggplot(batch, mapping = aes(x = x1, y = x2, color = as.factor(eigen_index0))) + geom_point()
```


## Final Plot

```{r}
ggplot() + geom_point(data = eigenbatch, mapping = aes(x = x1, y = x2, color = as.factor(eigen_index)))
```




