---
title: "Demo"
author: "Taqi"
date: "4/24/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../R/header.R")
.src(d = 1)
install.packages("RMAT")
```

```{r}
spectrum.scatterplot <- function(array, ..., mat_str = ""){
  # Process spectrum of the matrix/ensemble
  if(class(array) == "list" || class(array) == "matrix"){
    array_spectrum <- spectrum(array, ...)
  }
  # Else, the array is a precomputed spectrum (avoid computational waste for multiple visualizations)
  else{
    array_spectrum <- array
  }
  # Infer plot title string from which type of array (matrix/ensemble)
  title_str <- .plot_title(class(array), prefix = "Spectrum", mat_str)
  # Plot parameters
  order <- array_spectrum[["Order"]]
  # Plot
  array_spectrum %>%
    ggplot() +
    geom_point(mapping = aes(x = Re, y = Im, color = order), alpha = 0.75) +
    scale_color_continuous(type = "viridis") +
    labs(x = "Re", y = "Im", title = paste(title_str,sep = "")) +
    coord_fixed()
}
```

```{r}
ens <- RME_norm(N = 10, symm = F, size = 550)
ens_spec <- ens %>% spectrum_par(components = TRUE)
ens_spec <- ens_spec %>% mutate(isLargest = (function(x){x == 1})(Order))
```

```{r}
ens <- RME_unif(N = 10, min = 0, max = 1, symm = F, size = 550)
ens_spec <- ens %>% spectrum_par(components = TRUE)
ens_spec <- ens_spec %>% mutate(isLargest = (function(x){x == 1})(Order))
```


```{r}
ens_spec %>% 
  ggplot() +
  geom_jitter(mapping = aes(x = Re, y = Im, color = Order, shape = isLargest), alpha = 0.4) +
  scale_color_continuous(type = "viridis") +
  scale_shape_manual(values = c("circle","cross")) +
  labs(x = "Re", y = "Im", title = paste("Spectrum of a Standard Normal Matrix Ensemble",sep = "")) +
  coord_fixed()
```

