---
title: "Main Demo"
author: "Ali Taqi"
date: "2/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RMAT)
library(tidyverse)
```

```{r}
?RM_norm
?RM_erdos
?RM_stoch
?RM_beta
?RM_trid
```

```{r}
P <- RME_norm(N = 25, size = 200)
#spectrum(P) 
P %>% dispersion(pairs = "lower") %>% dispersion.histogram(metric = "abs_diff")
P %>% dispersion(pairs = "consecutive") %>% dispersion.histogram(metric = "abs_diff")
```

```{r}
P <- RME_norm(N = 10, cplx = T, herm = T, size = 100)
P %>% spectrum(components = T, sort_norms = F) %>% spectrum.scatterplot()
P %>% spectrum(components = T, sort_norms = T) %>% spectrum.scatterplot()
P %>% dispersion(pairs = "lower") %>% dispersion.scatterplot(metric = "abs_diff")
P %>% dispersion(pairs = "consecutive") %>% dispersion.scatterplot(pairs = "consecutive", metric = "id_diff_norm")
P %>% dispersion(pairs = "consecutive") %>% dispersion.scatterplot(pairs = "consecutive", metric = "abs_diff")
P %>% dispersion(pairs = "consecutive") %>% dispersion.histogram(metric = "abs_diff")
```

```{r}
# P %>% spectrum(components = T, sortByNorm = F)
# P %>% spectrum(components = T, sortByNorm = T)
```


```{r}
# P <- RM_norm(N = 10, complex = T)
# .visualize_normal_entries(P)
# P <- RM_erdos(N = 10, p = 0.5)
# .visualize_entries(P)
```

