

#=================================================================================#
#                             RANDOM MATRIX ENSEMBLES
#=================================================================================#


#' @title Generate an ensemble of normal random matrices
#'
#' @description Given a matrix class, this function returns an ensemble of that particular class of matrix.
#'   While random matrices usually do not exude unique properties on their own, they do indeed have
#'   deterministic properties (usually in spectral statistics) at the ensemble level.
#'
#' @param mat_type an RMAT random matrix function or identifier string
#' @param args a list of arguments to feed the RMAT random matrix function
#' @param ensemble_size the number of matrices to be simulated in the ensemble
#' @return A list of matrices generated by the input matrix class and arguments.
#' @examples
#' # Generate an ensemble of standard normal 3x3 matrices of size 20
#'
#' ## Using RMAT functions directly
#' ensemble <- RME(RM_norm, args = c(N = 3, mean = 0, sd = 1), ensemble_size = 20)
#'
#' ## Equivalent call
#' ensemble <- RME("norm", args = c(N = 3, mean = 0, sd = 1), ensemble_size = 20)
#'
RME_norm <- function(N, ..., size){lapply(X = rep(N, size), FUN = RM_norm, ...)}

RME_beta <- function(N, ..., size){lapply(X = rep(N, size), FUN = RM_beta, ...)}

RME_stoch <- function(N, ..., size){lapply(X = rep(N, size), FUN = RM_stoch, ...)}

RME_erdos <- function(N, ..., size){lapply(X = rep(N, size), FUN = RM_erdos, ...)}




